// Generated by scripts/generate-articles.mjs. Do not edit directly.

export type GeneratedArticle = {
  slug: string;
  title: string;
  description: string;
  topic: string;
  date: string;
  displayDate: string;
  fieldNote: string;
  marginNote: string;
  body: string;
};

export const generatedArticles: GeneratedArticle[] = [];
